title: Omar Ramos Escoto
# description: Smart Product Designer
theme: jekyll-theme-minimal
logo: /assets/images/omar_ramos_circle.png

sass:
  style: compressed

# Navigation Bar
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Coursework"
    url: "/coursework/"
  - title: "Resume"
    url: "/resume/"